### PR TITLE
Esnook 36 create an endpoint to get the parks associated to a client

### PR DESCRIPTION
**Pull request by RafaelCintaFerreira**
Implement the Schemas and Models for the Client and Park entities.
Implement the following endpoints:
 - /park, with optional parameters for owner id and location
 - /park/{park_id}, get park by id
 - /client, with the optional parameters to filter by id
Implementation for a database connection (commented out while bd not up)

### CODE REVIEW

**Review by zegameiro — COMMENTED** [review]
I don't know if keeping the variables used to define the database tables in the utils file is the best way to organize the code

**Comment by RafaelCintaFerreira** [comment]
> I don't know if keeping the variables used to define the database tables in the utils file is the best way to organize the code

Thank you for your input! I see your point about defining the table variables (like id_, name, phone, etc.) in the utils.py file. The intention behind placing them there was to promote reuse and avoid repetition across multiple modules. Since the column definitions (like id_ and name) are common to several tables (a.k.a. utilitarian variables), centralizing them in one file (a.k.a. utilitarian file) seemed like a way to make the code more maintainable and easier to extend.

However, I understand that this could lead to confusion or poor organization in the long run, especially if the number of shared columns grows or if unrelated modules end up importing unnecessary variables. An alternative approach could be:

 - Keeping common columns within each module: Defining the columns directly in each model file, makes each model more self-contained and easier to understand. This way, the variables are closer to the table definition and specific to each context with the drawback of repeating the code for each entity and for each entity representation.

 - Grouping related columns in utils.py: Another option would be to group only closely related sets of columns (like id_ and name) in specific files, rather than putting all reusable columns in utils.py. For example, a common_columns.py for generic columns like id_ or metadata would be more semantically meaningful, but generate more boiler files without other benefits.

 - Use of lambda expressions: Utilizing lambda expressions can keep the spirit of the utils.py having only functions rather than variables. Of course this has the drawback of ofuscating the code without benefits.
 

I can adjust the structure based on your preferred style or approach. Let me know if you think organizing them differently might benefit clarity!

**Review by zegameiro — COMMENTED** [review]
Thank you for providing me some options
I think that the second option that you present would make the code more organized instead of being stored in a utils.py

**Review by zegameiro — APPROVED** [review]
Everything seems right and organized.

**Review by fungame2270 — APPROVED** [review]
lgtm :+1:

**Pull request merged**
